@echo off
echo Resetting network settings...
echo Releasing IP address...
ipconfig /release
echo Renewing IP address...
ipconfig /renew
echo Flushing DNS cache...
ipconfig /flushdns
echo Resetting Winsock catalog...
netsh winsock reset
echo Resetting TCP/IP stack...
netsh int ip reset
echo Network settings have been reset. It's recommended to restart your computer. not necessary but it's better to restart
pause
